# Generated by Django 3.0 on 2021-07-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.PositiveSmallIntegerField(verbose_name='Número da casa a ser visitada'),
        ),
    ]
